[
  {
    "description": "",
    "elements": [
      {
        "after": [
          {
            "match": {
              "location": "support/ruby/env.rb:5"
            },
            "result": {
              "duration": 375275,
              "error_message": "Failing after hook (RuntimeError)\n./support/ruby/env.rb:6:in `After'",
              "status": "failed"
            }
          }
        ],
        "description": "",
        "id": ";",
        "keyword": "Scenario",
        "line": 3,
        "name": "",
        "steps": [
          {
            "keyword": "Given ",
            "line": 4,
            "match": {
              "location": "support/ruby/env.rb:9"
            },
            "name": "this step passes",
            "result": {
              "duration": 67598,
              "status": "passed"
            }
          }
        ],
        "tags": [
          {
            "line": 2,
            "name": "@failing-after"
          }
        ],
        "type": "scenario"
      }
    ],
    "id": "",
    "keyword": "Feature",
    "line": 1,
    "name": "",
    "uri": "features/failing-after-hook.feature"
  }
]
